language: cpp
compiler:
  - gcc
  - clang

before_install:
 - test -n $CC && unset CC
 - test -n $CXX && unset CXX
 - eval "${MATRIX_EVAL}"

env:
  global:
  matrix:
    - MPI=mpich
    - MPI=openmpi


branches:
  only:
    - master